# FindLuaJIT.cmake

FIND_PATH(LUAJIT_INCLUDE_DIR luajit.h
    PATHS
    /usr/include/luajit-2.1
    NO_DEFAULT_PATH
)

FIND_LIBRARY(LUAJIT_LIBRARY
    NAMES luajit-5.1
    PATHS
    /usr/lib/x86_64-linux-gnu
    NO_DEFAULT_PATH
)

IF(LUAJIT_INCLUDE_DIR AND LUAJIT_LIBRARY)
    SET(LUAJIT_FOUND TRUE)
    SET(LUAJIT_INCLUDE_DIRS ${LUAJIT_INCLUDE_DIR})
    SET(LUAJIT_LIBRARIES ${LUAJIT_LIBRARY})
    
    # Set these for compatibility
    SET(LUA_FOUND TRUE)
    SET(LUA_INCLUDE_DIR ${LUAJIT_INCLUDE_DIR})
    SET(LUA_LIBRARIES ${LUAJIT_LIBRARY})
    SET(LUA_VERSION_STRING "5.1")
    SET(LUA_VERSION_MAJOR 5)
    SET(LUA_VERSION_MINOR 1)
    
    MESSAGE(STATUS "Found LuaJIT: ${LUAJIT_LIBRARY}")
    MESSAGE(STATUS "  includes: ${LUAJIT_INCLUDE_DIR}")
ENDIF()

MARK_AS_ADVANCED(
    LUAJIT_INCLUDE_DIR
    LUAJIT_LIBRARY
)
